version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - habit-game-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/habit-game
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - habit-game-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - habit-game-network
    restart: unless-stopped

networks:
  habit-game-network:
    driver: bridge

volumes:
  mongodb-data: 